services:
  - type: web
    name: pythonstoreapi
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host=0.0.0.0 --port=$PORT
    envVars:
      - key: PORT
        value: 10000
      - key: SECRET_KEY
        generateValue: true
    healthCheckPath: /health
